[supabase]
db_url = "postgresql://postgres:nilonsdatabase1962@db.xltjimtqikfgfacryyef.supabase.co:5432/postgres"

[fb_access_token]
ACCESS_TOKEN = "EAFj9NZBCpuFQBPVNP9K96VmF0YCvd20lsvidfWPTvi7ZBQvZB91dItskvgrfPkY1WMy3iI8naODmB2m834LZBGWsHXVYw70YBCrKefrlHibN1X5gLnRylVgtCjqbBLraWDdS6ZCeVt4EH7VioCVKgcyoQrIZCa9DZBm3WDyjrPainGgSjMAB9lVXvGqGUUI"

[cloudinary]
cloud_name="dvbiqmhoo"
api_key="358538431434132"
api_secret="MTnwuudPzdiDZ96_tpL_7A60zZ0"

[connections.postgresql]
dialect = "postgresql"
host = "db.xltjimtqikfgfacryyef.supabase.co"
port = "5432"
database = "postgres"
username = "postgres"
user = "postgres"
password = "nilonsdatabase1962"